spring.application.name=loan_data_project

server.port=${PORT:8080}

# DataBase Configuration
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ddl-auto=update → Updates the database schema automatically.
# show-sql=true → Prints SQL queries in the console (useful during development).
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# file.upload-dir=D:/FileStorage/loan_data_project/uploads
file.upload-dir=${FILE_UPLOAD_DIR:/tmp/loan_data_project/uploads}

jwt.secret = ${JWT_KEY}
jwt.expiration=86400000

ai.review.base-url=${AI_REVIEW_BASE_URL}