spring.application.name=loan_data_project

# DataBase Configuration
spring.datasource.url = jdbc:postgresql://localhost:5432/Loan_Data_Verification
spring.datasource.username = postgres
spring.datasource.password = Ramarao@456

# ddl-auto=update → Updates the database schema automatically.
# show-sql=true → Prints SQL queries in the console (useful during development).
spring.jpa.hibernate.ddl-auto = update 
spring.jpa.show-sql = true

file.upload-dir=D:/FileStorage/loan_data_project/uploads

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yTG9hbkRhdGFQcm9qZWNjdDIwMjY=
jwt.expiration=86400000

ai.review.base-url=http://localhost:8001